### ISSUE TITLE
Please fix KillRate sign

### ISSUE THREAD

**Issue by XiangZhao969** [PocketMine-PHP7/KillRate-PHP7#1]
This happens when i place [STATS] sign
[Server] [02:25:02] critical> Could not execute task aliuly\killrate\common\PluginCallbackTask: Class pocketmine\nbt\tag\StringTag not found
[Server] [02:25:02] critical> ClassNotFoundException: "Class pocketmine\nbt\tag\StringTag not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
[Server] [02:25:06] critical> Could not execute task aliuly\killrate\common\PluginCallbackTask: Class pocketmine\nbt\tag\StringTag not found
[Server] [02:25:06] critical> ClassNotFoundException: "Class pocketmine\nbt\tag\StringTag not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

**Comment by flaxues** [comment]
Which version are you runnning? I think you are using php5

**Comment by XiangZhao969** [comment]
That version doesn't work anymore :( can you fix?

**Comment by flaxues** [comment]
What error does the php5 version give?

**Comment by XiangZhao969** [comment]
[Server] [12:21:29] system> Enabling KillRate v2.1.1
[Server] [12:21:29] critical> ClassNotFoundException: "Class aliuly\killrate\common\mc2 not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
[Server] [12:21:29] system> Disabling KillRate v2.1.1

**Comment by flaxues** [comment]
https://transfer.sh/qyW47/killrate-php5.phar

This one works i think

**Comment by flaxues** [comment]
Since you didn't react anymore I think it worked :)

**Comment by XiangZhao969** [comment]
The plugin can now be loaded butsigns still doesn't work

**Comment by flaxues** [comment]
Could you put you're debug level in pocketmine.yml to 3 and restart the server and place a sign with [STATS] on it and post the response of the server

**Comment by flaxues** [comment]
And could you try this phar

https://transfer.sh/Weu3Y/killrate-php5.phar

**Comment by XiangZhao969** [comment]
[Server] [01:54:47] [Server thread/DEBUG]: Level "flat" took 154.94ms, setting tick rate to 3 ticks
[Server] [01:54:47] [Server thread/DEBUG]: Raising level "flat" tick rate to 2 ticks
[Server] [01:54:47] [Server thread/DEBUG]: Raising level "flat" tick rate to 1 ticks
[Server] [01:54:56] [Server thread/DEBUG]: Level "CybusHUB1" took 80.32ms, setting tick rate to 2 ticks
[Server] [01:54:56] [Server thread/DEBUG]: Level "CybusHUB1" took 101.59ms, setting tick rate to 3 ticks
[Server] [01:54:57] [Server thread/DEBUG]: Raising level "CybusHUB1" tick rate to 2 ticks
[Server] [01:54:57] [Server thread/DEBUG]: Raising level "CybusHUB1" tick rate to 1 ticks

**Comment by flaxues** [comment]
Did you place the sign with [STATS] on it? I only see worlds loading...

**Comment by XiangZhao969** [comment]
Yes

**Comment by flaxues** [comment]
Did you enabled signs in the config?

**Comment by XiangZhao969** [comment]
Yes, here is my config 
---
version: 2.1.1
features:
  '# signs': enable/disable signs
  signs: true
  '# ranks': Enable support for RankUp plugin
  ranks: false
  '# achievements': Enable PocketMine achievements
  achievements: true
  '# kill-streak': Enable kill-streak tracking.
  kill-streak: true
  '# rewards': award money.
  rewards: true
settings:
  '# points': award points.
  points: true
  '# min-kills': Minimum number of kills before declaring a kill-streak
  min-kills: 7
  '# reset-on-death': Reset counters on death.
  reset-on-death: false
  '# creative': track creative kills.
  creative: false
  '# dynamic-updates': Update signs.
  dynamic-updates: 80
  '# default-rank': Default rank (when resetting ranks)
  default-rank: false
values:
  <Example>:
  - money
  - points
  '*':
  - 1
  - 10
  Player:
  - 100
  - 100
formats:
  default: '{sname} {count}'
  names: '{n}.{player}'
  scores: '{count}'
database:
  '# backend': Use SQLiteMgr or MySqlMgr
  backend: SQLiteMgr
  '# MySql': MySQL settings.
  MySql:
    host: localhost
    user: nobody
    password: secret
    database: KillRateDb
    port: 3306
signs:
  '[STATS]': stats
  '[ONLINE TOPS]': online-tops
  '[RANKINGS]': rankings
  '[RANKNAMES]': rankings-names
  '[RANKPOINTS]': rankings-points
  '[TOPNAMES]': online-top-names
  '[TOPPOINTS]': online-top-points
...
